name: Loominance
options:
  bundleIdPrefix: com.loominance
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  Loominance:
    type: application
    platform: macOS
    sources:
      - path: Loominance
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loominance.app
        INFOPLIST_FILE: Loominance/Info.plist
        CODE_SIGN_ENTITLEMENTS: Loominance/Loominance.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.video"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
